# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm run test

    - name: Build
      run: npm run build
  deploy:
    runs-on: ubuntu-latest
    # When application is successfully tested and build has been generated
    # Then we can start with deployment
    needs: build
    steps:
      # Download previously shared build
      - name: Get artifact
      # Set the credentials from repository settings/secrets
      - name: Configure AWS credentials
      # Copy the files from build folder to the S3 bucket
      - name: Deploy to S3
  release:
    runs-on: ubuntu-latest
    # We specify that deploys needs to
    # finish before we create a release
    needs: deploy
    steps:
      # Download previously shared build
      - name: Get artifact
      # Zip the build using external action
      - name: Zip build
      # Upload as an artifact of the current workflow
      - name: Upload build zip artifact
      # Make official GitHub release which will trigger
      # sending the mail with link for access
      - name: Release
